### ISSUE TITLE
bug: Clicking links in editor causes crash

### ISSUE THREAD

**Issue by PyroTech03** [lodicolo/Intersect-Engine#11]
### Release

0.8.0-beta.76

### Platform

win-x64

### Application

Intersect Editor

### Description

Was trying to click the "Chat commands" link in one of the event editors. Once clicking, causes crash.

### Error Logs
```
2023-10-04 06:28:23.876 [Error] Win32Exception: An error occurred trying to start process 'http://www.ascensiongamedev.com/community/topic/749-event-text-variables/' with working directory 'C:\Users\windowsuser\Downloads\intersect-win-x64-full-0.8.0-beta.76+build.96a9fc876797a251c966a08bcde59fe57d6d85e5\Client and Editor'. The system cannot find the file specified.
    Stack:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandChangePlayerLabel.lblStringTextVariables_Click(Object sender, EventArgs e) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_ChangePlayerLabel.cs:line 84
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


--------------------------------------------------------------------------------
2023-10-04 06:28:56.012 [Error] Win32Exception: An error occurred trying to start process 'http://www.ascensiongamedev.com/community/topic/749-event-text-variables/' with working directory 'C:\Users\windowsuser\Downloads\intersect-win-x64-full-0.8.0-beta.76+build.96a9fc876797a251c966a08bcde59fe57d6d85e5\Client and Editor'. The system cannot find the file specified.
    Stack:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandText.lblCommands_Click(Object sender, EventArgs e) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Text.cs:line 77
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


--------------------------------------------------------------------------------
```

### Non-Error Logs
```
2023-10-04 06:28:42.105 [Info] Connecting to 127.0.0.1:5400...

--------------------------------------------------------------------------------
2023-10-04 06:28:42.372 [Info] Connection approved [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------
2023-10-04 06:28:42.392 [Info] Connected [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------
2023-10-04 06:28:56.004 [Error] Win32Exception: An error occurred trying to start process 'http://www.ascensiongamedev.com/community/topic/749-event-text-variables/' with working directory 'C:\Users\mgurl\Downloads\intersect-win-x64-full-0.8.0-beta.76+build.96a9fc876797a251c966a08bcde59fe57d6d85e5\Client and Editor'. The system cannot find the file specified.
    Stack:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommandText.lblCommands_Click(Object sender, EventArgs e) in D:\a\Intersect-Engine\Intersect-Engine\Intersect.Editor\Forms\Editors\Events\Event Commands\EventCommand_Text.cs:line 77
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


--------------------------------------------------------------------------------
```

### Steps to Reproduce

open editor with link, such as chat box event command.

Click link.

Crash.

### Did you find any workaround?

None

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by pandinocoder** [comment]
Should be fixed in 96bfcf56d0003757c83a4299d4c7ecfe3117b673 released as https://github.com/lodicolo/Intersect-Engine/releases/tag/v0.8.0-beta.102.

Leaving open for verification.
